server:
    port: 8088
spring:
    kafka:
        bootstrap-servers: 10.100.1.166:9092
        listener:
            missing-topics-fatal: false
            type: batch
        producer:
            acks: 1
            batch-size: 10000
            buffer-memory: 33554432
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            retries: 1
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

#日志文件配置
logging:
    config: classpath:logback.xml

